### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by qarlosalberto** [toem/impulse.vscode#1]
Hi,
I have installed impulse-vscode and Java. My setup:

- Ubuntu 20.10
- openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.10)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.10, mixed mode, sharing)
- VSCode 1.57.1

When I open my VCD file impulse-vscode freezes:

![image](https://user-images.githubusercontent.com/5955143/125275574-80cf0e80-e30f-11eb-80c0-a10d385f39c1.png)

My VCD:

```
 $date Fri Jul 24 13:51:17 2020 $end
 $version libsigrok 0.6.0-git-c03aaf342c3f $end
 $comment
   Acquisition with 6/6 channels at 200 kHz
 $end
 $timescale 1 us $end
 $scope module libsigrok $end
 $var wire 1 ! D0 $end
 $var wire 1 " D1 $end
 $var wire 1 # D2 $end
 $var wire 1 $ D3 $end
 $var real 64 % A0 $end
 $var real 64 & A1 $end
 $upscope $end
 $enddefinitions $end
 
 #0 1! 0" 0# 1$ r-10 % r0 &
 #5 0! 1" 1# 0$ r3.090169906616211 &
 #10 r5.877852439880371 &
 #15 r8.090169906616211 &
 #20 1! 0" 1$ r9.510564804077148 &
 #25 1" r10 % r10 &
 #30 r9.510564804077148 &
 #35 r8.090169906616211 &
 #40 0! r5.877852439880371 &
 #45 0" 0# 0$ r3.090169906616211 &
 #50 r-10 % r-3.216245298855018e-15 &
 #55 1" 1# 1$ r-3.090169906616211 &
 #60 1! r-5.877852439880371 &
 #65 r-8.090169906616211 &
 #70 r-9.510564804077148 &
 #75 r10 % r-10 &
 #80 0" 0# 0$ r-9.510564804077148 &
 #85 0! 1" 1# 1$ r-8.090169906616211 &
 #90 r-5.877852439880371 &
 #95 0$ r-3.090169906616211 &
 #100
```

**Comment by thomasAtToem** [comment]
Hi Carlos,

not fully sure , whats in here.

1) Your vcd has a 1 space indention, seems that the recognition of our vcd reader (Value Change Dump in Default Group) fails here.
Click the Show/Hide icon on the right side and select the vcd reader manually in the left top field.

Next click the "Open view dialog" icon and add a new view.

2) You talk about a freeze. Is it really a freeze or just an emtpy view ?

thanks,
thomas

**Comment by qarlosalberto** [comment]
It works fine! My signal area was hidden. Thanks!
