### ISSUE TITLE
Impulse viewer will no longer open

### ISSUE THREAD

**Issue by dine909** [toem/impulse.vscode#5]
And causes VSCode to crash extensions hosts

Have tried reinstalling it, and using an example VCD to test, bit it jus sits there blank with the fans speeding up until VSCode implodes.

However, it does work in a remote container copy of VSCode.

How can i reset the extension correctly?

**Comment by thomasAtToem** [comment]
HI,
sorry to hear.
I remember a similar problem, but long ago. We need to put an updated release on the servers.
I guess that the preferences are somehow broken.
This can be resolved by deleting the files under ~/.config/Code/User/workspaceStorage/*/toem-de.impulse/

thanks,
thomas

**Comment by dine909** [comment]
Thanks for the speedy reply Thomas, that did the trick

in my case it was located here 

```
rm -rf ~/.vscode/extensions/toem-de.impulse-0.3.4
```

**Comment by dine909** [comment]
This worked for a single session, then it failed again after restarting VSCode.  But retrying from this point on has not worked.

I think it could be related to a network port perhaps (might be conflicting with something on my system?), is there anything i can do to help to produce useful debug information for us to look deeper into it?  

The workaround of using it in a VSCode remote container instance is still working for now so there's that.

Many thanks in advance

**Comment by thomasAtToem** [comment]
There will be a new major release end of this or next week. 
So I would propose to wait for it and work with the remote conainter in the meanwhile.

**Comment by dine909** [comment]
Awesome news! - Can i suggest that interpolation is set to off by default?

Also thanks for your work and support, I appreciate it.

**Comment by thomasAtToem** [comment]
New release 0.3.5 available. Please check !
